config/routes.rb
ProfitApp::Application.routes.draw do
  root 'static_pages#home'
  match '/profitcrunch', to: 'static_pages#profitcrunch', via: 'get'
  match '/gross_profit_calculator', to: 'static_pages#gross_profit', via: 'get'
  match '/markup_calculator', to: 'static_pages#markup', via: 'get'
  match '/sales_lift_calculator', to: 'static_pages#sales_lift', via: 'get'
  match '/promotion_recap_calculator', to: 'static_pages#promotion_recap', via: 'get'

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
	def index
		@static_pages = [root_url, profitcrunch_url, gross_profit_calculator_url, markup_calculator_url, sales_lift_calculator_url, promotion_recap_calculator_url]
		respond_to do |format|
			format.xml
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def profitcrunch
  end

  def gross_profit
  end

  def markup
  end

  def sales_lift
  end

  def promotion_recap
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "ProfitCruncher"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52827113-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<header role="banner">
	<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#main-navbar">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "ProfitCruncher", root_path, id: "logo", class: "navbar-brand" %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div id="main-navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path, class: "active" %></li>
				<li><%= link_to "ProfitCrunch", profitcrunch_path %></li>
				<li><%= link_to "Gross Profit Margin Calculator", gross_profit_calculator_path %></li>
				<li><%= link_to "Markup Calculator", markup_calculator_path %></li>
        <li class="dropdown">
        	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Sales Promotion Calculators <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Sales Lift Calculator", sales_lift_calculator_path %></li>
            <li><%= link_to "Promotion Recap", promotion_recap_calculator_path %></li>
          </ul>
        </li>
			</ul>
		</div>
	</div>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title><%= full_title(yield(:title)) %></title>
  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
 	 	<%= render 'layouts/shim' %>
 	 	<meta name="viewport" content="width=device-width, initial-scale=1">
 	 	<meta name="keywords" content="<%= yield(:keywords) %>">
 	 	<meta name="description" content="<%= yield(:description) %>">
 	 	<%= render 'layouts/google_analytics' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/static_pages/gross_profit.html.erb
<% provide(:title, 'Gross Profit Margin Calculator') %>
<% provide(:keywords, 'gross, profit, margin, calculator, business, financial') %>
<% provide(:description, 'Business calculators for owners, managers, and sales forces that are formatted for any device. Try the Gross Profit Margin Calculator.') %>
<h1>Gross Profit Margin Calculator</h1>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
			<div class="col-xs-8 col-xs-offset-2">
				<label for="cost">Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control calc-cost" id="cost">
				</div>
				<label for="ptc">Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control calc-ptc" id="ptc">
				</div>
				<label for="gross-profit">Gross Profit Margin:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control calc-margin" id="gross-profit">
  				<span class="input-group-addon">%</span>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/home.html.erb
<% provide(:keywords, 'gross, profit, margin, calculator, business, markup, sales, lift, analysis, price, calculation, financial') %>
<% provide(:description, 'Business calculators for owners, managers, and sales forces that are formatted for any device. Maximize every sale with profit calculators that drive results.') %>

<div class="center jumbotron">
		<h1>ProfitCruncher</h1>

		<p>Start managing profits today with handy calculators for business owners, managers, and sales forces.  We provide business calculators that you can access on any device, so you can maximize every sale.  Maximize every sale with profit calculators that drive results.</p>
</div>

app/views/static_pages/markup.html.erb
<% provide(:title, 'Markup Calculator') %>
<% provide(:keywords, 'gross, profit, markup, calculator, business, financial') %>
<% provide(:description, 'Business calculators for owners, managers, and sales forces that are formatted for any device. Try the Markup Calculator.') %>
<h1>Markup Calculator</h1>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
			<div class="col-xs-8 col-xs-offset-2">
				<label for="cost">Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control calc-cost" id="cost">
				</div>
				<label for="ptc">Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control calc-ptc" id="ptc">
				</div>
				<label for="markup">Markup:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control calc-markup" id="markup">
  				<span class="input-group-addon">%</span>
  			</div>	
			</div>
		</div>
	</div>

app/views/static_pages/profitcrunch.html.erb
<% provide(:title, 'ProfitCrunch') %>
<% provide(:keywords, 'gross, profit, margin, markup, calculator, business, financial') %>
<% provide(:description, 'Business calculators for owners, managers, and sales forces that are formatted for any device. ProfitCrunch with Profit Margin and Markup calculators.') %>
<h1>ProfitCrunch</h1>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
			<div class="col-xs-6">
				<label for="units-case">Units/Case:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-units-case" id="units-case">
				</div>
				<label for="case-cost">Case Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-case-cost" id="case-cost">
				</div>
				<label for="unit-cost">Unit Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-cost" id="disabledInput unit-cost" disabled>
				</div>
				<label for="ptc">Unit Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-ptc" id="ptc">
				</div>
			</div>
			<div class="col-xs-6">
				<label for="total-profit">Total Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-total-profit" id="disabledInput total-profit" disabled>
				</div>
				<label for="profit">Unit Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-profit" id="disabledInput profit" disabled>
				</div>
				<label for="gross-profit">Gross Profit Margin:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-gross-profit" id="disabledInput gross-profit" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="markup">Markup:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-markup" id="disabledInput markup" disabled>
  				<span class="input-group-addon">%</span>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/promotion_recap.html.erb
<% provide(:title, 'Promotion Recap Calculator') %>
<% provide(:keywords, 'gross, profit, margin, calculator, business, financial, sales, promotion') %>
<% provide(:description, 'Business calculators for owners, managers, and sales forces that are formatted for any device. Analyze your sales promotion with the Promotion Recap Calculator.') %>
<h1>Promotion Recap</h1>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<h2 class="toggle">
				<a href="#">How to <span class="caret"></span></a>
			</h2>
			<p>If you've run a promotion by putting units on sale, you may want to compare your sales at promotional pricing against your sales at regular pricing.  How many more units did you sell at promotional pricing and was your Total Profit greater?  Promotion Recap lets you compare Regular and Promotional sales data so you can plan better promotions.
			</p>
		</div>

		<div class="col-xs-12 col-sm-6 col-md-4">
			<div class="col-xs-6">
				<h2><strong><em>Regular</em></strong></h2>
				<label for="reg-units-case">Units/Case:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-units-case" id="reg-units-case">
				</div>
				<label for="reg-units-sold">Units Sold:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-units-sold" id="reg-units-sold">
				</div>
				<label for="reg-case-cost">Case Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-case-cost" id="reg-case-cost">
				</div>
				<label for="reg-unit-cost">Unit Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-cost" id="disabledInput reg-unit-cost" disabled>
				</div>
				<label for="reg-ptc">Unit Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-ptc" id="reg-ptc">
				</div>
				<label for="reg-total-profit">Total Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-total-profit-recap" id="disabledInput reg-total-profit" disabled>
				</div>
				<label for="reg-unit-profit">Unit Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-profit" id="disabledInput reg-unit-profit" disabled>
				</div>
				<label for="reg-gross-profit">Gross Profit Margin:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-gross-profit" id="disabledInput reg-gross-profit" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="reg-markup">Markup:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-markup" id="disabledInput reg-markup" disabled>
  				<span class="input-group-addon">%</span>
				</div>
			</div>
			<div class="col-xs-6">
				<h2><strong><em>Promotion</em></strong></h2>
				<label for="promo-units-case">Units/Case:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-profitcrunch-units-case" id="promo-units-case">
				</div>
				<label for="promo-units-sold">Units Sold:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-units-sold" id="promo-units-sold">
				</div>
				<label for="promo-case-cost">Case Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-case-cost" id="promo-case-cost">
				</div>
				<label for="promo-unit-cost">Unit Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-unit-cost" id="disabledInput promo-unit-cost" disabled>
				</div>
				<label for="promo-ptc">Unit Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-unit-ptc" id="promo-ptc">
				</div>
				<label for="promo-total-profit">Total Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-total-profit-recap" id="disabledInput promo-total-profit" disabled>
				</div>
				<label for="promo-unit-profit">Unit Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-unit-profit" id="disabledInput promo-unit-profit" disabled>
				</div>
				<label for="promo-gross-profit">Gross Profit Margin:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-profitcrunch-gross-profit" id="disabledInput promo-gross-profit" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="promo-markup">Markup:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-profitcrunch-markup" id="disabledInput promo-markup" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="lift">Profit Recap:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profit-recap" id="disabledInput lift" disabled>
  				<span class="input-group-addon">%</span>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/sales_lift.html.erb
<% provide(:title, 'Sales Lift Calculator') %>
<% provide(:keywords, 'gross, profit, margin, calculator, business, financial, sales, promotion, lift') %>
<% provide(:description, 'Business calculators for owners, managers, and sales forces that are formatted for any device. Plan your sales promotion smarter - know your Break Even Lift.') %>
<h1>Sales Lift Calculator</h1>

	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<h2 class="toggle">
				<a href="#">How to <span class="caret"></span></a>
			</h2>
			<p>If you're putting an item on sale you'll hopefully sell more units.  How many units do you need to sell to retain the same profit, your Break Even Lift?  Use the Sales Lift Calculator to determine the percentage of additional sales needed to retain the same Total Profit.  
			</p>
		</div>

		<div class="col-xs-12 col-sm-6 col-md-4">
			<div class="col-xs-6">
				<h2><strong><em>Regular</em></strong></h2>
				<label for="reg-units-case">Units/Case:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-units-case" id="reg-units-case">
				</div>
				<label for="reg-case-cost">Case Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-case-cost" id="reg-case-cost">
				</div>
				<label for="reg-unit-cost">Unit Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-cost" id="disabledInput reg-unit-cost" disabled>
				</div>
				<label for="reg-ptc">Unit Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-ptc" id="reg-ptc">
				</div>
				<label for="reg-total-profit">Total Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-total-profit" id="disabledInput reg-total-profit" disabled>
				</div>
				<label for="reg-unit-profit">Unit Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control profitcrunch-unit-profit" id="disabledInput reg-unit-profit" disabled>
				</div>
				<label for="reg-gross-profit">Gross Profit Margin:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-gross-profit" id="disabledInput reg-gross-profit" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="reg-markup">Markup:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control profitcrunch-markup" id="disabledInput reg-markup" disabled>
  				<span class="input-group-addon">%</span>
				</div>
			</div>
			<div class="col-xs-6">
				<h2><strong><em>Promotion</em></strong></h2>
				<label for="promo-units-case">Units/Case:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-profitcrunch-units-case" id="promo-units-case">
				</div>
				<label for="promo-case-cost">Case Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-case-cost" id="promo-case-cost">
				</div>
				<label for="promo-unit-cost">Unit Cost:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-unit-cost" id="disabledInput promo-unit-cost" disabled>
				</div>
				<label for="promo-ptc">Unit Sell Price:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-unit-ptc" id="promo-ptc">
				</div>
				<label for="promo-total-profit">Total Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-total-profit" id="disabledInput promo-total-profit" disabled>
				</div>
				<label for="promo-unit-profit">Unit Profit:</label>
				<div class="input-group">
  				<span class="input-group-addon">$</span>
  				<input type="number" step=".01" class="form-control promo-profitcrunch-unit-profit" id="disabledInput promo-unit-profit" disabled>
				</div>
				<label for="promo-gross-profit">Gross Profit Margin:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-profitcrunch-gross-profit" id="disabledInput promo-gross-profit" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="promo-markup">Markup:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-profitcrunch-markup" id="disabledInput promo-markup" disabled>
  				<span class="input-group-addon">%</span>
				</div>
				<label for="lift">Break Even Lift:</label>
				<div class="input-group">
  				<input type="number" step=".01" class="form-control promo-lift" id="disabledInput lift" disabled>
  				<span class="input-group-addon">%</span>
				</div>
			</div>
		</div>
	</div>